### ISSUE TITLE
Internal Server Error for IP query in X.X.X/24 format

### ISSUE THREAD

**Issue by jumpifnotzero** [icann/icann-rdap#11]
Query for /ip/229.0.0/24 causes an error in the logs

2023-06-05T21:17:56.420225Z ERROR tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=0 ms

Interestingly, I used the 224.0.0/24 to create the data (rdap-srv-data network --cidr 224.0.0/24).

I don't think it is related, but server has objects for 224.0.0.7/32, 224.0.0.0/24 and 224.0.0.0/8.

**Comment by anewton1998** [comment]
Fixed in commit f9598ead8a1bc993abd930edf3e3e4c661900455 when it is merged.

**Comment by anewton1998** [comment]
Merged in #20
