### ISSUE TITLE
LDH domain queries should be case-insensitive

### ISSUE THREAD

**Issue by jumpifnotzero** [icann/icann-rdap#13]
/rdap/domain/BIZ and /rdap/domain/biz should match the same domain object.

To reproduce, create a domain object `rdap-srv-data domain --ldh BIZ` and reload the server.  A query for /rdap/domain/biz will return 404 whereas a query for /rdap/domain/BIZ will return 200.

**Comment by anewton1998** [comment]
This should be fixed by commit 07c10cecf0483b68effeb21e0019937345fc41bd

**Comment by anewton1998** [comment]
Merged in #20
