### ISSUE TITLE
rdap --url does not work when RDAP_BASE_URL is set

### ISSUE THREAD

**Issue by jumpifnotzero** [icann/icann-rdap#15]
The error message says --url cannot be used with --base-url, however this is incorrect as --base-url is not provided.
I would expect --url to work even if RDAP_BASE_URL is set.

**Comment by anewton1998** [comment]
this will be fixed when commit 84fe6e586b6403e5d4f3addb77487c7c764614a2 is merged

**Comment by anewton1998** [comment]
Merged in #20
