### ISSUE TITLE
Server should match FQDN with trailing dot

### ISSUE THREAD

**Issue by jumpifnotzero** [icann/icann-rdap#16]
A query for /domain/example. should match the domain object "example" if following the robustness principle.

IANA receives approx. one hundred queries an hour to whois for domains ending in a trailing dot - that we currently match.

**Comment by anewton1998** [comment]
This will be fixed by commit 07c10cecf0483b68effeb21e0019937345fc41bd when it is merged.

**Comment by anewton1998** [comment]
Merged in #20
