### ISSUE TITLE
Support for accessing HttpData from ParsingErrorInfo

### ISSUE THREAD

**Issue by ddnomad** [icann/icann-rdap#39]
In `icann_rdap_client::query::request::rdap_request` function, `icann_rdap_common::cache::HttpData` is only accessible if a response received from an upstream is a valid JSON. See this code snippet:

https://github.com/icann/icann-rdap/blob/8b8478cd9b03c7b2a1fa24124aae4b3b7391aa02/icann-rdap-client/src/query/request.rs#L40-L71

This makes it challenging to retrieve HTTP response status and redirection location when running with `follow_redirects=false` from `ClientConfig` (e.g. when using a [rdap_bootstrap_server](https://github.com/arineng/rdap_bootstrap_server) project to determine authoritative RDAP server for a given request per [RFC7484](https://datatracker.ietf.org/doc/html/rfc7484)). See this:

https://github.com/icann/icann-rdap/blob/8b8478cd9b03c7b2a1fa24124aae4b3b7391aa02/icann-rdap-common/src/client.rs#L30-L31

It would be nice to be able to access `icann_rdap_common::cache::HttpData` as part of `icann_rdap_client::ParsingErrorInfo` that is inside `icann_rdap_client::RdapClientError::ParsingError`.

The easiest way to achieve it would be to move lines 43-55 in `icann_rdap_client::query::request::rdap_request` outside of `if let Ok(rdap_json) = json {` condition and make it a separate field as part of `icann_rdap_client::ParsingErrorInfo` (which would make fields `text`, `content_length`, `content_type`, `url` redundant).

Would this be something that the maintainers be willing to accommodate? I am open to create a pull request that makes the necessary changes if needed.

**Comment by anewton1998** [comment]
Yes, this sounds like a very good idea, and a PR would be welcome. Please PR against the 'dev' branch.

Also, you may be interested to know that the icann-rdap-srv crate included in this project can now act as a redirect server using the IANA bootstrap files.
