### ISSUE TITLE
incorrect SpecWarn regarding self links in top-level nameserver objects

### ISSUE THREAD

**Issue by mau14333** [icann/icann-rdap#59]
Situation: A nameserver query receives a response that looks like this.
```
{
  [...],
  "objectClassName": "nameserver",
  "links": [
    {
      "rel": "self",
      "href": "[...]",
      "type": "application/rdap+json",
      "value": "[...]"
    }
  ]
  "notices": [
    {
      "links": [
        {
          "rel": "terms-of-service",
          "href": "[...]",
          "type": "text/html",
          "value": "[...]"
        }
      ],
      "title": "Terms of service"
    },
    [...]
  ],
  [...]
}
```
Even though the self link is present, the client will report `SpecWarn: RFC 9083 recommends self links for all object classes` in this case.

It seems to me that the cause can be found here:
https://github.com/icann/icann-rdap/blob/5f945c88bae665b280272c0defbcf5648431fa93/icann-rdap-common/src/check/types.rs#L87-L96
The root type is checked against `Nameserver`, but the direct parent type is not, meaning the terms-of-service link embedded in "notices" will also satisfy this condition and be recognized as a missing self link.

**Comment by anewton1998** [comment]
Fixed in #60
